### ISSUE TITLE
Revoir le plan

### ISSUE THREAD

**Issue by florianorpeliere** [BearsJS/JSTraining_Slides#12]
Preface
1. Introduction to JavaScript
   1.1 Core JavaScript
   1.2 Client-Side JavaScript
2. Lexical Structure
   2.1 Character Set
   2.2 Comments
   2.3 Literals
   2.4 Identifiers and Reserved Words
   2.5 Optional Semicolons
3. Types, Values, and Variables
   3.1 Numbers
   3.2 Text
   3.3 Boolean Values
   3.4 null and undefined
   3.5 The Global Object
   3.6 Wrapper Objects
   3.7 Immutable Primitive Values and Mutable Object References
   3.8 Type Conversions
   3.9 Variable Declaration
   3.10 Variable Scope
4. Expressions and Operators
   4.1 Primary Expressions
   4.2 Object and Array Initializers
   4.3 Function Definition Expressions
   4.4 Property Access Expressions
   4.5 Invocation Expressions
   4.6 Object Creation Expressions
   4.7 Operator Overview
   4.8 Arithmetic Expressions
   4.9 Relational Expressions
   4.10 Logical Expressions
   4.11 Assignment Expressions
   4.12 Evaluation Expressions
   4.13 Miscellaneous Operators
5. Statements
   5.1 Expression Statements
   5.2 Compound and Empty Statements
   5.3 Declaration Statements
   5.4 Conditionals
   5.5 Loops
   5.6 Jumps
   5.7 Miscellaneous Statements
   5.8 Summary of JavaScript Statements
6. Objects
   6.1 Creating Objects
   6.2 Querying and Setting Properties
   6.3 Deleting Properties
   6.4 Testing Properties
   6.5 Enumerating Properties
   6.6 Property Getters and Setters
   6.7 Property Attributes
   6.8 Object Attributes
   6.9 Serializing Objects
   6.10 Object Methods
7. Arrays
   7.1 Creating Arrays
   7.2 Reading and Writing Array Elements
   7.3 Sparse Arrays
   7.4 Array Length
   7.5 Adding and Deleting Array Elements
   7.6 Iterating Arrays
   7.7 Multidimensional Arrays
   7.8 Array Methods
   7.9 ECMAScript 5 Array Methods
   7.10 Array Type
   7.11 Array-Like Objects
   7.12 Strings As Arrays
8. Functions
   8.1 Defining Functions
   8.2 Invoking Functions
   8.3 Function Arguments and Parameters
   8.4 Functions As Values
   8.5 Functions As Namespaces
   8.6 Closures
   8.7 Function Properties, Methods, and Constructor
   8.8 Functional Programming
9. Classes and Modules
   9.1 Classes and Prototypes
   9.2 Classes and Constructors
   9.3 Java-Style Classes in JavaScript
   9.4 Augmenting Classes
   9.5 Classes and Types
   9.6 Object-Oriented Techniques in JavaScript
   9.7 Subclasses
   9.8 Classes in ECMAScript 5
   9.9 Modules
10. Pattern Matching with Regular Expressions
    10.1 Defining Regular Expressions
    10.2 String Methods for Pattern Matching
    10.3 The RegExp Object
11. JavaScript Subsets and Extensions
    11.1 JavaScript Subsets
    11.2 Constants and Scoped Variables
    11.3 Destructuring Assignment
    11.4 Iteration
    11.5 Shorthand Functions
    11.6 Multiple Catch Clauses
    11.7 E4X: ECMAScript for XML
12. Server-Side JavaScript
    12.1 Scripting Java with Rhino
    12.2 Asynchronous I/O with Node
13. JavaScript in Web Browsers
    13.1 Client-Side JavaScript
    13.2 Embedding JavaScript in HTML
    13.3 Execution of JavaScript Programs
    13.4 Compatibility and Interoperability
    13.5 Accessibility
    13.6 Security
    13.7 Client-Side Frameworks
14. The Window Object
    14.1 Timers
    14.2 Browser Location and Navigation
    14.3 Browsing History
    14.4 Browser and Screen Information
    14.5 Dialog Boxes
    14.6 Error Handling
    14.7 Document Elements As Window Properties
    14.8 Multiple Windows and Frames
15. Scripting Documents
    15.1 Overview of the DOM
    15.2 Selecting Document Elements
    15.3 Document Structure and Traversal
    15.4 Attributes
    15.5 Element Content
    15.6 Creating, Inserting, and Deleting Nodes
    15.7 Example: Generating a Table of Contents
    15.8 Document and Element Geometry and Scrolling
    15.9 HTML Forms
    15.10 Other Document Features
16. Scripting CSS
    16.1 Overview of CSS
    16.2 Important CSS Properties
    16.3 Scripting Inline Styles
    16.4 Querying Computed Styles
    16.5 Scripting CSS Classes
    16.6 Scripting Stylesheets
17. Handling Events
    17.1 Types of Events
    17.2 Registering Event Handlers
    17.3 Event Handler Invocation
    17.4 Document Load Events
    17.5 Mouse Events
    17.6 Mousewheel Events
    17.7 Drag and Drop Events
    17.8 Text Events
    17.9 Keyboard Events
18. Scripted HTTP
    18.1 Using XMLHttpRequest
    18.2 HTTP by <script>: JSONP
    18.3 Comet with Server-Sent Events
19. The jQuery Library 
    19.1 jQuery Basics
    19.2 jQuery Getters and Setters
    19.3 Altering Document Structure
    19.4 Handling Events with jQuery
    19.5 Animated Effects
    19.6 Ajax with jQuery
    19.7 Utility Functions
    19.8 jQuery Selectors and Selection Methods
    19.9 Extending jQuery with Plug-ins
    19.10 The jQuery UI Library
20. Client-Side Storage
    20.1 localStorage and sessionStorage
    20.2 Cookies
    20.3 IE userData Persistence
    20.4 Application Storage and Offline Webapps
21. Scripted Media and Graphics
    21.1 Scripting Images
    21.2 Scripting Audio and Video
    21.3 SVG: Scalable Vector Graphics
    21.4 Graphics in a <canvas>
22. HTML5 APIs
    22.1 Geolocation
    22.2 History Management
    22.3 Cross-Origin Messaging
    22.4 Web Workers

22.5 Typed Arrays and ArrayBuffers
22.6 Blobs
22.7 The Filesystem API
22.8 Client-Side Databases
22.9 Web Sockets

**Comment by SiegfriedEhret** [comment]
"Optional Semicolons" => Semicolons.

**Comment by SiegfriedEhret** [comment]
9.8 Classes in ECMAScript 5 => ECMAScript 6 ?

**Comment by SiegfriedEhret** [comment]
11.7 E4X: ECMAScript for XML => What ?
