### ISSUE TITLE
Les exemples de typeof ne sont pas parlants

### ISSUE THREAD

**Issue by SiegfriedEhret** [BearsJS/JSTraining_Slides#3]
Il faut mettre des exemples réels.

Genre `typeof 9000` au lieu de `typeof Nombre` (surtout que les variables sont introduites un peu plus loin).

**Comment by AshDevFr** [comment]
On devrait peut être voir les variables avant même si voir les variables sans les type c'est chaud
Et apres faire un truc genre : 

``` js
var n = 5;
typeof n; //'number'
```

**Comment by AshDevFr** [comment]
PR : #6
