### ISSUE TITLE
Exemple du if

### ISSUE THREAD

**Issue by SiegfriedEhret** [BearsJS/JSTraining_Slides#4]
http://localhost:3000/#/4/5

```
if (condition) {
  instruction1
} [else if (autre condition){
  instruction2
}] [else {
  instruction2
}]
```
- [ ] ne pas mettre les crochets (perturbant mais je comprends pourquoi => les mettre en couleurs ?)
- [ ] mettre instruction3 dans le else

**Comment by AshDevFr** [comment]
On peut virer les crochets mais c'est aussi un moyen d'introduire ce genre d'ecritures qu'on retrouve dans toutes les docs.
Pour les couleurs ça va être chaud dans highlightJS

Pour instruction 3 oui je vais changer ça :)
